### ISSUE TITLE
Error messages are overwritten

### ISSUE THREAD

**Issue by nymous** [WikiJourney/wikijourney_api#2]
If the place doesn't exist, the error here https://github.com/WikiJourney/wikijourney_api/blob/master/index.php#L32 is overwritten by the "non numeric" error https://github.com/WikiJourney/wikijourney_api/blob/master/index.php#L63.
This is because `$user_latitude` and `$user_longitude` are not set.

**Comment by sylvainar** [comment]
Fixed in 64695fd930feb654bef67307185432c33237cd39
Thanks !
